version: '3'
services:
  frontend:
    build: ./frontend //
    ports:
      - "3000:80"
    networks:
      - my-network
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - my-network

networks:
  my-network:
